### ISSUE TITLE
No network I/O for passthrough NICs

### ISSUE THREAD

**Issue by neodark-ffs** [mittelab/proxmox-via-prometheus-dashboard#5]
Is there any way to update the dashboard to scrape Network I/O from physical NICs passed directly to Proxmox VMs via PCI passthrough?   

![Screenshot 2023-08-24 105819](https://github.com/mittelab/proxmox-via-prometheus-dashboard/assets/138724976/6694511a-61d1-4cf9-a041-96ea95977ec0)

Or, does proxmox not provide this data via their API? 

Very cool dashboard, and work gents!

Thanks!

**Comment by guruevi** [comment]
@neodark-ffs No, since the metrics aren't available to the host, if you pass through the physical NIC, then the hypervisor 'loses' control over the NIC. You would have to monitor at the guest level

**Comment by g5pw** [comment]
I can confirm this, sorry. If you need this feature, you can run node_exporter inside the VM
